In [13]:
%load_ext autoreload
%autoreload 2
%reload_ext autoreload

In [14]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import src.crs as crs

# 1. Reco Process

In [15]:
data_path = "data/apt_1.xlsx"
xlsx = pd.read_excel(data_path, header=None,
                     skiprows=2, engine="openpyxl")

xlsx.head()

,0,1,2,3,4,5,6,7,8,9,...,105,106,107,108,109,110,111,112,113,114
0,- '0시 0분'은 0시0분 ~ 0시 14분 59초 동안 사용한 양을 입력,NaN,NaN,NaN,NaN,NaN,B1,아파트1,아파트1,아파트1,...,아파트1,아파트1,아파트1,아파트1,아파트1,아파트1,아파트1,아파트1,아파트1,아파트1
1,NaN,NaN,NaN,NaN,NaN,NaN,B1_1_동,104,104,104,...,102,103,103,103,103,103,103,103,103,103
2,연/월/일,연,월,일,시,분,B1_1_호수,1206,303,1307,...,901,1905,503,1504,606,903,1106,705,1505,406
3,20180501,2018,5,1,0,0,NaN,0.085,0.016,0.052,...,0.098,0.053,0.091,0.08,0.207,0.132,0.039,0.034,0.055,0.075
4,20180501,2018,5,1,0,15,NaN,0.086,0.049,0.053,...,0.13,0.048,0.055,0.084,0.14,0.149,0.037,0.032,0.082,0.096

In [16]:
# 2. data-preprocessing
p, m = crs.utils.data_preprocessing(xlsx)

/Users/formegusto/Desktop/idoformegusto/development/research/distribution-by-contribution/src/crs/utils/data_preprocessing.py:26: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  datas_df[household_name] = household_df[col][3:].to_list()
/Users/formegusto/Desktop/idoformegusto/development/research/distribution-by-contribution/src/crs/utils/data_preprocessing.py:49: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  month_usage_df[name] = [

In [17]:
# 3. bill calc
min_per = 10
max_per = 80

bc_result = crs.utils.bill_calc(m, p, min_per, max_per)

가구 수: 108 / 평균: 288 / 표준편차: 120 / 변동계수: 42
가구 수: 108 / 평균: 260 / 표준편차: 97 / 변동계수: 37
가구 수: 108 / 평균: 273 / 표준편차: 92 / 변동계수: 34
가구 수: 108 / 평균: 254 / 표준편차: 88 / 변동계수: 35
가구 수: 108 / 평균: 240 / 표준편차: 89 / 변동계수: 37
가구 수: 108 / 평균: 233 / 표준편차: 89 / 변동계수: 38
가구 수: 108 / 평균: 326 / 표준편차: 135 / 변동계수: 41
가구 수: 108 / 평균: 362 / 표준편차: 153 / 변동계수: 42
가구 수: 108 / 평균: 231 / 표준편차: 92 / 변동계수: 40
가구 수: 108 / 평균: 238 / 표준편차: 96 / 변동계수: 40
가구 수: 108 / 평균: 251 / 표준편차: 106 / 변동계수: 42
가구 수: 108 / 평균: 288 / 표준편차: 111 / 변동계수: 39

In [22]:
# 4. mean analysis
m_result = crs.utils.mean_analysis(m, p, min_per, max_per)

가구 수: 108 / 평균: 270 / 표준편차: 96 / 변동계수: 36

In [23]:
# 5. similarity analysis
s_result = crs.utils.similarity_analysis(m, p, min_per, max_per)

가구 수: 108 / 평균: 245 / 표준편차: 85 / 변동계수: 35

({'params': {'min_per': 10, 'max_per': 80},
  'information': [{'count': 108, 'mean': 270, 'std': 96, 'rsd': 36}],
  'households_bill': {'comp': [    아파트1-101-1002  아파트1-101-104  아파트1-101-1102  아파트1-101-1202  아파트1-101-1302  \
    10        39010.0       86240.0        34160.0        30580.0        91920.0
    11        39460.0       86690.0        34610.0        31030.0        92370.0
    12        39930.0       87160.0        35080.0        31500.0        92840.0
    13        40400.0       87630.0        35550.0        31970.0        93310.0
    14        40890.0       88120.0        36040.0        32460.0        93800.0
    ..            ...           ...            ...            ...            ...
    76       134740.0      181970.0       129890.0       126310.0       187650.0
    77       140150.0      187380.0       135300.0       131720.0       193060.0
    78       146050.0      193280.0       141200.0       137620.0       198960.0
    79       152500.0      199730.0       147650.0       144070.0       205410.0
    80       159580.0      206810.0       154730.0       151150.0       212490.0

        아파트1-101-1401  아파트1-101-1403  아파트1-101-1502  아파트1-101-1504  아파트1-101-1602  \
    10        50590.0        65330.0        20420.0        56270.0        57120.0
    11        51040.0        65780.0        20870.0        56720.0        57570.0
    12        51510.0        66250.0        21340.0        57190.0        58040.0
    13        51980.0        66720.0        21810.0        57660.0        58510.0
    14        52470.0        67210.0        22300.0        58150.0        59000.0
    ..            ...            ...            ...            ...            ...
    76       146320.0       161060.0       116150.0       152000.0       152850.0
    77       151730.0       166470.0       121560.0       157410.0       158260.0
    78       157630.0       172370.0       127460.0       163310.0       164160.0
    79       164080.0       178820.0       133910.0       169760.0       170610.0
    80       171160.0       185900.0       140990.0       176840.0       177690.0

        ...  아파트1-104-303  아파트1-104-404  아파트1-104-408  아파트1-104-503  아파트1-104-507  \
    10  ...        6630.0       10840.0        5300.0       16610.0       15690.0
    11  ...        7080.0       11290.0        5750.0       17060.0       16140.0
    12  ...        7550.0       11760.0        6220.0       17530.0       16610.0
    13  ...        8020.0       12230.0        6690.0       18000.0       17080.0
    14  ...        8510.0       12720.0        7180.0       18490.0       17570.0
    ..  ...           ...           ...           ...           ...           ...
    76  ...      102360.0      106570.0      101030.0      112340.0      111420.0
    77  ...      107770.0      111980.0      106440.0      117750.0      116830.0
    78  ...      113670.0      117880.0      112340.0      123650.0      122730.0
    79  ...      120120.0      124330.0      118790.0      130100.0      129180.0
    80  ...      127200.0      131410.0      125870.0      137180.0      136260.0

        아파트1-104-606  아파트1-104-705  아파트1-104-708  아파트1-104-902  아파트1-104-905
    10       14660.0       40690.0       17850.0       10530.0       13110.0
    11       15110.0       41140.0       18300.0       10980.0       13560.0
    12       15580.0       41610.0       18770.0       11450.0       14030.0
    13       16050.0       42080.0       19240.0       11920.0       14500.0
    14       16540.0       42570.0       19730.0       12410.0       14990.0
    ..           ...           ...           ...           ...           ...
    76      110390.0      136420.0      113580.0      106260.0      108840.0
    77      115800.0      141830.0      118990.0      111670.0      114250.0
    78      121700.0      147730.0      124890.0      117570.0      120150.0
    79      128150.0      154180.0      131340.0      124020.0      126600.0
    80      135230.0      161260.0      138420.0      131100.0      133680.0

    [71 rows x 108 columns]],
   'single': [    아파트1-101-1002  아파트1-101-104  아파트1-101-1102  아파트1-101-1202  아파트1-101-1302  \
    10        32219.0       69319.0        28429.0        25629.0        73689.0
    11        32773.0       69873.0        28983.0        26183.0        74243.0
    12        33342.0       70442.0        29552.0        26752.0        74812.0
    13        33921.0       71021.0        30131.0        27331.0        75391.0
    14        34516.0       71616.0        30726.0        27926.0        75986.0
    ..            ...           ...            ...            ...            ...
    76       229884.0      266984.0       226094.0       223294.0       271354.0
    77       241741.0      278841.0       237951.0       235151.0       283211.0
    78       254672.0      291772.0       250882.0       248082.0       296142.0
    79       268836.0      305936.0       265046.0       262246.0       310306.0
    80       284416.0      321516.0       280626.0       277826.0       325886.0

        아파트1-101-1401  아파트1-101-1403  아파트1-101-1502  아파트1-101-1504  아파트1-101-1602  \
    10        41259.0        52769.0        18379.0        45699.0        46359.0
    11        41813.0        53323.0        18933.0        46253.0        46913.0
    12        42382.0        53892.0        19502.0        46822.0        47482.0
    13        42961.0        54471.0        20081.0        47401.0        48061.0
    14        43556.0        55066.0        20676.0        47996.0        48656.0
    ..            ...            ...            ...            ...            ...
    76       238924.0       250434.0       216044.0       243364.0       244024.0
    77       250781.0       262291.0       227901.0       255221.0       255881.0
    78       263712.0       275222.0       240832.0       268152.0       268812.0
    79       277876.0       289386.0       254996.0       282316.0       282976.0
    80       293456.0       304966.0       270576.0       297896.0       298556.0

        ...  아파트1-104-303  아파트1-104-404  아파트1-104-408  아파트1-104-503  아파트1-104-507  \
    10  ...        6859.0       10389.0        5569.0       15199.0       14429.0
    11  ...        7413.0       10943.0        6123.0       15753.0       14983.0
    12  ...        7982.0       11512.0        6692.0       16322.0       15552.0
    13  ...        8561.0       12091.0        7271.0       16901.0       16131.0
    14  ...        9156.0       12686.0        7866.0       17496.0       16726.0
    ..  ...           ...           ...           ...           ...           ...
    76  ...      204524.0      208054.0      203234.0      212864.0      212094.0
    77  ...      216381.0      219911.0      215091.0      224721.0      223951.0
    78  ...      229312.0      232842.0      228022.0      237652.0      236882.0
    79  ...      243476.0      247006.0      242186.0      251816.0      251046.0
    80  ...      259056.0      262586.0      257766.0      267396.0      266626.0

        아파트1-104-606  아파트1-104-705  아파트1-104-708  아파트1-104-902  아파트1-104-905
    10       13569.0       33529.0       16239.0       10129.0       12279.0
    11       14123.0       34083.0       16793.0       10683.0       12833.0
    12       14692.0       34652.0       17362.0       11252.0       13402.0
    13       15271.0       35231.0       17941.0       11831.0       13981.0
    14       15866.0       35826.0       18536.0       12426.0       14576.0
    ..           ...           ...           ...           ...           ...
    76      211234.0      231194.0      213904.0      207794.0      209944.0
    77      223091.0      243051.0      225761.0      219651.0      221801.0
    78      236022.0      255982.0      238692.0      232582.0      234732.0
    79      250186.0      270146.0      252856.0      246746.0      248896.0
    80      265766.0      285726.0      268436.0      262326.0      264476.0

    [71 rows x 108 columns]]},
  'bill': {'comp':           10         11         12         13         14         15  \
   1  4602650.0  4651250.0  4702010.0  4752770.0  4805690.0  4858610.0

             16         17         18         19  ...          71          72  \
   1  4912610.0  4967690.0  5023850.0  5081090.0  ...  12613010.0  13013690.0

              73          74          75          76          77          78  \
   1  13442450.0  13904690.0  14402570.0  14941490.0  15525770.0  16162970.0

              79          80
   1  16859570.0  17624210.0

   [1 rows x 71 columns],
   'single':           10         11         12         13         14         15  \
   1  3793290.0  3853080.0  3914600.0  3977110.0  4041330.0  4107030.0

             16         17         18         19  ...          71          72  \
   1  4174320.0  4243210.0  4313690.0  4385780.0  ...  20064120.0  20934500.0

              73          74          75          76          77          78  \
   1  21869470.0  22875910.0  23963390.0  25141120.0  26421640.0  27818200.0

              79          80
   1  29347870.0  31030540.0

   [1 rows x 71 columns]},
  'public_bill': {'comp':          10        11        12        13        14        15        16  \
   1  449930.0  499210.0  549490.0  600630.0  652880.0  705970.0  760160.0

            17        18        19  ...         71         72         73  \
   1  815450.0  871810.0  929240.0  ...  8460300.0  8860900.0  9290420.0

             74          75          76          77          78          79  \
   1  9752120.0  10250120.0  10788770.0  11373410.0  12010320.0  12706910.0

              80
   1  13472190.0

   [1 rows x 71 columns],
   'single':          10        11        12        13        14        15        16  \
   1  421120.0  480910.0  542430.0  604940.0  669160.0  734860.0  802150.0

            17        18         19  ...          71          72          73  \
   1  871040.0  941520.0  1013610.0  ...  16691950.0  17562330.0  18497300.0

              74          75          76          77          78          79  \
   1  19503740.0  20591220.0  21768950.0  23049470.0  24446030.0  25975700.0

              80
   1  27658370.0

   [1 rows x 71 columns]}},
 {'positive_count': {'comp':     10   11   12   13   14   15   16   17   18   19  ...     71     72     73  \
   1  4.0  4.0  4.0  5.0  6.0  8.0  8.0  8.0  9.0  9.0  ...  108.0  108.0  108.0

         74     75     76     77     78     79     80
   1  108.0  108.0  108.0  108.0  108.0  108.0  108.0

   [1 rows x 71 columns],
   'single':       10     11     12     13     14     15     16     17    18    19  ...  \
   1  104.0  104.0  104.0  103.0  102.0  100.0  100.0  100.0  99.0  99.0  ...

       71   72   73   74   75   76   77   78   79   80
   1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

   [1 rows x 71 columns]},
  'loss_ratio': {'comp':       10     11     12     13     14     15     16     17     18     19  ...  \
   1  119.0  118.0  117.0  117.0  116.0  116.0  115.0  114.0  114.0  113.0  ...

        71    72    73    74    75    76    77    78    79    80
   1  62.0  62.0  61.0  60.0  60.0  59.0  58.0  58.0  57.0  56.0

   [1 rows x 71 columns],
   'single':      10    11    12    13    14    15    16    17    18    19  ...     71  \
   1  85.0  85.0  85.0  86.0  86.0  87.0  88.0  88.0  88.0  89.0  ...  162.0

         72     73     74     75     76     77     78     79     80
   1  163.0  165.0  167.0  169.0  170.0  172.0  174.0  176.0  178.0

   [1 rows x 71 columns]},
  'pos_change_per': {'bill': array([33.]),
   'public_bill': array([13.]),
   'positive_count': array([33.]),
   'loss_ratio': array([33.])}})